---
title: 'Green Regional Path paper: First results'
author: "Daniel S. Hain"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    code_folding: hide
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
---

```{r, setup, include=FALSE}
### general options
Sys.setenv(LANG = "en")
options("scipen" = 100, "digits" = 4) # override R's tendency to use scientific notation

### Clean workspace
rm(list=ls())
graphics.off()

### Load packages (maybe need to be installed first)
# Standard
library(tidyverse) # General DS toolkit
library(magrittr) # For advanced piping
```

# Skill data

```{r}
skill_labels <- read_rds('../temp/skill_labels.rds')
```

```{r}
var_year = c('2018', '2020')
```

```{r}
data <- tibble()

for(i in length(var_year)){
  data %>% bind_rows(read_rds(paste0('../temp/list_skills_', var_year[i], '.rds')) %>% mutate(year = var_year[i]))
}

data %<>% left_join(skill_labels, by = 'skill_label')
```


```{r}
data %>% pull(job_id) %>% n_distinct()
```

```{r}
data %>% count(skill_label, sort = TRUE) %>% head(100)
```



